"""Engine constants — re-exported from src.constants for backward compatibility."""

from src.constants import (  # noqa: F401, E402
    BATCH_SIZE,
    BATCH_TUNE_1_2_CORE,
    BATCH_TUNE_4_CORE,
    BATCH_TUNE_8_CORE,
    BATCH_TUNE_16_CORE,
    BATCH_TUNE_32_CORE,
    BATCH_TUNE_64_PLUS_CORE,
    COMPRESSION_AUTO_THRESHOLD,
    COMPRESSION_FORCE_SINGLE_THRESHOLD,
    CPU_CACHE_INTERVAL_SEC,
    DATA_LOG_SAVE_FREQUENCY,
    DEDUP_MAX_RECENT_SIZE,
    ERROR_LOG_INTERVAL_SEC,
    MATCH_BATCH_FLUSH_THRESHOLD,
    MEMORY_CRITICAL_THRESHOLD_MB,
    MEMORY_DOWNGRADE_COOLDOWN_SEC,
    MEMORY_HIGH_THRESHOLD_MB,
    PROGRESS_INTERVAL_COUNT,
    PROGRESS_INTERVAL_COUNT_DEFAULT,
    PROGRESS_INTERVAL_SEC,
)
